export enum Classification {
  PORIFERA = "PORIFERA",
  CNIDARIA = "CNIDARIA",
  PLATYHELMINTHES = "PLATYHELMINTHES",
  NEMATODA = "NEMATODA",
  ANNELIDA = "ANNELIDA",
  MOLLUSCA = "MOLLUSCA",
  ARTHROPODA = "ARTHROPODA",
  ECHINODERMATA = "ECHINODERMATA",
  VERTEBRATA = "VERTEBRATA",
  CEPHALOCHORDATA = "CEPHALOCHORDATA",
  UROCHORDATA = "UROCHORDATA",
  NONE = "NONE"
}
