export enum NationType {
  ALL = 'ALL',
  KINGDOM = "KINGDOM",
  EMPIRE = "EMPIRE",
  FEDERATION = "FEDERATION",
  DUCHY = "DUCHY",
  CITY_STATE = "CITY_STATE",
  REPUBLIC = "REPUBLIC",
  NONE = "NONE"
}
